### ISSUE TITLE
Fix front end encoding issues 

### ISSUE THREAD

**Issue by amchaney** [cognitive-catalyst/annotation-assist#13]
Error log indicating front-end encoding issue:

2016-05-02T15:16:30.41-0500 [App/0]      ERR 23.246.234.102 - - [02/May/2016 20:16:30] "POST /api/topic HTTP/1.1" 200 -
2016-05-02T15:16:31.35-0500 [RTR/1]      OUT themis-c.stage1.mybluemix.net - [02/05/2016:20:16:30 +0000] "POST /api/get_question HTTP/1.1" 500 12 21484 "http://themis-c.stage1.mybluemix.net/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36" 50.97.127.167:50541 x_forwarded_for:"9.66.209.199" x_forwarded_proto:"http" vcap_request_id:7c637334-d462-4706-7b1b-01918ad52f4b response_time:0.802931339 app_id:c16ae2c8-7716-4d2f-9923-8a5290d66042 x_global_transaction_id:"95638537"
2016-05-02T15:16:31.38-0500 [App/0]      ERR 23.246.234.102 - - [02/May/2016 20:16:31] "POST /api/get_question HTTP/1.1" 500 -
2016-05-02T15:16:31.38-0500 [App/0]      ERR Traceback (most recent call last):
2016-05-02T15:16:31.38-0500 [App/0]      ERR   File "/home/vcap/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1836, in **call**
2016-05-02T15:16:31.38-0500 [App/0]      ERR     return self.wsgi_app(environ, start_response)
2016-05-02T15:16:31.38-0500 [App/0]      ERR   File "/home/vcap/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
2016-05-02T15:16:31.38-0500 [App/0]      ERR     response = self.make_response(self.handle_exception(e))
2016-05-02T15:16:31.38-0500 [App/0]      ERR   File "/home/vcap/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
2016-05-02T15:16:31.38-0500 [App/0]      ERR     reraise(exc_type, exc_value, tb)
2016-05-02T15:16:31.38-0500 [App/0]      ERR   File "/home/vcap/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
2016-05-02T15:16:31.38-0500 [App/0]      ERR     response = self.full_dispatch_request()
2016-05-02T15:16:31.38-0500 [App/0]      ERR   File "/home/vcap/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
2016-05-02T15:16:31.38-0500 [App/0]      ERR     rv = self.handle_user_exception(e)
2016-05-02T15:16:31.38-0500 [App/0]      ERR   File "/home/vcap/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
2016-05-02T15:16:31.38-0500 [App/0]      ERR     reraise(exc_type, exc_value, tb)
2016-05-02T15:16:31.38-0500 [App/0]      ERR   File "/home/vcap/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
2016-05-02T15:16:31.38-0500 [App/0]      ERR     rv = self.dispatch_request()
2016-05-02T15:16:31.38-0500 [App/0]      ERR   File "/home/vcap/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
2016-05-02T15:16:31.38-0500 [App/0]      ERR     return self.view_functions[rule.endpoint](**req.view_args)
2016-05-02T15:16:31.38-0500 [App/0]      ERR   File "/home/vcap/app/api.py", line 40, in annotate
2016-05-02T15:16:31.38-0500 [App/0]      ERR     question_data = db_ops.get_question(system_name)
2016-05-02T15:16:31.38-0500 [App/0]      ERR   File "/home/vcap/app/db_ops.py", line 255, in get_question
2016-05-02T15:16:31.38-0500 [App/0]      ERR     return {'question': question, "similar": get_similar(qdata[2])}
2016-05-02T15:16:31.38-0500 [App/0]      ERR   File "/home/vcap/app/db_ops.py", line 220, in get_similar
2016-05-02T15:16:31.38-0500 [App/0]      ERR     cmd = "Select {0} FROM \"Questions\" WHERE System_Answer='{1}' AND IS_ANNOTATED ='1' AND ANNOTATION_SCORE>'{2}' ".format(','.join(output_fields), answer.replace("'", "''"), acceptable_annotation_score - 1)
2016-05-02T15:16:31.38-0500 [App/0]      ERR UnicodeEncodeError: 'ascii' codec can't encode characters in position 12-14: ordinal not in range(128)
2016-05-02T15:16:37.67-0500 [RTR/2]

**Comment by amblock** [comment]
Fixed on dev
